name: Deploy to Vercel

on:
  push:
    branches:
      - master  # or any other branch as per your flow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name mentorconnect --public
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}